stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: |-
        mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rad304/example-rancher-project:${CICD_EXECUTION_SEQUENCE}
      # Optionally push to remote registry
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml