kind: Service
apiVersion: v1
metadata:
  name: rancher-project-staging-service
  namespace: staging
spec:
  selector:
    app: rancher-project-staging
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-rancher-project-staging
  namespace: staging
  labels:
    app: rancher-project-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher-project-staging
  template:
    metadata:
      labels:
        app: rancher-project-staging
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080