kind: Service
apiVersion: v1
metadata:
  name: rancher-project-service
  namespace: production
spec:
  selector:
    app: rancher-project
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-rancher-project
  namespace: production
  labels:
    app: rancher-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher-project
  template:
    metadata:
      labels:
        app: rancher-project
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080